# Generated by Django 2.0.6 on 2018-06-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
